### ISSUE TITLE
Doc Expansion and Clean up

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#171]
I want to get some feedback on areas were we can expand or clean up. 

I know there has been some talk in chat about this.

Please help us out through giving some feedback.

**Comment by PixelyIon** [comment]
Here's a bunch of things to do:
* Change from RTD to Github pages (More flexibility) or even the pommerman site
* This is the most functional and beautiful theme that I've seen yet https://github.com/squidfunk/mkdocs-material
* Rewrite the documentations in a more user-friendly and consistent way
* More GIFs (Because why not ?)

**Comment by PixelyIon** [comment]
https://github.com/MultiAgentLearning/playground/pull/176

**Comment by cinjon** [comment]
Closing due to the update merged in that @PixelyIon referenced.
